apiVersion: v1
kind: Service
metadata:
    name: mico-admin-service
    #namespace: mico-system
    labels:
        run: mico-admin
spec:
    loadBalancerIP: 40.68.22.7
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 80
    selector:
        run: mico-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mico-admin
    #namespace: mico-system
spec:
    selector:
        matchLabels:
            run: mico-admin
    replicas: 1
    template:
        metadata:
            #namespace: mico-system
            labels:
                run: mico-admin
        spec:
            containers:
                - name: mico-admin
                  image: ustmico/mico-admin
                  imagePullPolicy: Always
                  env:
                      - name: MICO_REST_API
                        value: 'mico-core.mico-system:8080'
                  ports:
                      - containerPort: 80
