---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mico-core
  namespace: mico-system
data:
  spring.profiles.active: prod
  application.properties: |-
    spring.data.neo4j.uri=bolt://neo4j.mico-system:7687
    kubernetes.prometheus.uri=http://prometheus.monitoring:9090/api/v1/query
    spring.redis.host=redis.mico-system
    spring.redis.port=6379
    kafka.bootstrap-servers=bootstrap.kafka:9092
    openfaas.gateway=http://gateway.openfaas:8080
---
apiVersion: v1
kind: Service
metadata:
  name: mico-core
  namespace: mico-system
  labels:
    run: mico-core
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    run: mico-core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mico-core
  namespace: mico-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mico-core
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      namespace: mico-system
      labels:
        run: mico-core
    spec:
      containers:
        - name: mico-core
          image: ustmico/mico-core
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: mico-core
                  key: spring.profiles.active
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 3
            failureThreshold: 3
