---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mico-core
  namespace: mico-system
data:
  application.properties: |-
    spring.profiles.active=prod
    spring.data.neo4j.uri=bolt://neo4j.mico-system:7687
    kubernetes.prometheus.uri=http://prometheus.monitoring:9090/api/v1/query
    spring.redis.host=redis.mico-system
    spring.redis.port=6379
---
apiVersion: v1
kind: Service
metadata:
  name: mico-core
  namespace: mico-system
  labels:
    run: mico-core
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: mico-core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mico-core
  namespace: mico-system
spec:
  selector:
    matchLabels:
      run: mico-core
  replicas: 1
  template:
    metadata:
      namespace: mico-system
      labels:
        run: mico-core
    spec:
      containers:
      - name: mico-core
        image: ustmico/mico-core
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
